<!-- Beginning of the Flag Selection; -->
                <div id="worldFlags" class="center">
                    <p id="flagTitle">Select a Flag to Find the Country</p>
                    <div id="flags">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/pirate-flag.jpg">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/pirate-flag.jpg">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/pirate-flag.jpg">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/pirate-flag.jpg">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/United_States_of_America.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                        <img id="flag001" src="images/smallFlags/Turkey.png">
                    </div>

                    <form method='POST' action='/'>
                        <fieldset id="flagFieldSet">
                            <legend>By these Facts</legend>
                            <input type='hidden' name='dummy' value='0'>
                            <label for='continent'>Continent</label>
                            <input type='input' name='continent' id='continent' value='<?php if(isset($_GET['continent'])) echo $_GET['continent'] ?>'> </br>
                            <label for='population'>Population</label>
                            <input type='input' name='population' id='population' value='<?php if(isset($_GET['population'])) echo $_GET['population'] ?>'> </br>
                            <label for='language'>Language</label>
                            <input type='input' name='language' id='language' value='<?php if(isset($_GET['language'])) echo $_GET['language'] ?>'> <br/>
                            <label for='capital'>Capital</label>
                            <input type='input' name='capital' id='capital' value='<?php if(isset($_GET['capital'])) echo $_GET['capital'] ?>'>
                        </fieldset>
                        <input type='submit' value="Pick One">
                    </form>
                </div>
